Subtitle-Downloader:
	msgfmt -o locales/zh-Hant/LC_MESSAGES/main.mo locales/zh-Hant/LC_MESSAGES/main
	msgfmt -o locales/zh-Hant/LC_MESSAGES/utils.helper.mo locales/zh-Hant/LC_MESSAGES/utils.helper
	msgfmt -o locales/zh-Hant/LC_MESSAGES/utils.io.mo locales/zh-Hant/LC_MESSAGES/utils.io
	msgfmt -o locales/zh-Hant/LC_MESSAGES/utils.subtitle.mo locales/zh-Hant/LC_MESSAGES/utils.subtitle
	msgfmt -o locales/zh-Hant/LC_MESSAGES/services.crunchyroll.mo locales/zh-Hant/LC_MESSAGES/services.crunchyroll
	msgfmt -o locales/zh-Hant/LC_MESSAGES/services.disneyplus.disneyplus.mo locales/zh-Hant/LC_MESSAGES/services.disneyplus.disneyplus
	msgfmt -o locales/zh-Hant/LC_MESSAGES/services.disneyplus.disneyplus_login.mo locales/zh-Hant/LC_MESSAGES/services.disneyplus.disneyplus_login
	msgfmt -o locales/zh-Hant/LC_MESSAGES/services.hbogoasia.mo locales/zh-Hant/LC_MESSAGES/services.hbogoasia
	msgfmt -o locales/zh-Hant/LC_MESSAGES/services.viu.mo locales/zh-Hant/LC_MESSAGES/services.viu
	msgfmt -o locales/zh-Hant/LC_MESSAGES/services.iqiyi.iqiyi.mo locales/zh-Hant/LC_MESSAGES/services.iqiyi.iqiyi
	msgfmt -o locales/zh-Hant/LC_MESSAGES/services.kktv.mo locales/zh-Hant/LC_MESSAGES/services.kktv
	msgfmt -o locales/zh-Hant/LC_MESSAGES/services.linetv.mo locales/zh-Hant/LC_MESSAGES/services.linetv
	msgfmt -o locales/zh-Hant/LC_MESSAGES/services.fridayvideo.mo locales/zh-Hant/LC_MESSAGES/services.fridayvideo
	msgfmt -o locales/zh-Hant/LC_MESSAGES/services.myvideo.mo locales/zh-Hant/LC_MESSAGES/services.myvideo
	msgfmt -o locales/zh-Hant/LC_MESSAGES/services.itunes.mo locales/zh-Hant/LC_MESSAGES/services.itunes
	msgfmt -o locales/zh-Hant/LC_MESSAGES/services.catchplay.mo locales/zh-Hant/LC_MESSAGES/services.catchplay
	msgfmt -o locales/zh-Hant/LC_MESSAGES/services.wetv.wetv.mo locales/zh-Hant/LC_MESSAGES/services.wetv.wetv
	msgfmt -o locales/zh-Hant/LC_MESSAGES/services.appletvplus.mo locales/zh-Hant/LC_MESSAGES/services.appletvplus
	msgfmt -o locales/zh-Hant/LC_MESSAGES/services.nowe.mo locales/zh-Hant/LC_MESSAGES/services.nowe
	msgfmt -o locales/zh-Hant/LC_MESSAGES/services.nowplayer.mo locales/zh-Hant/LC_MESSAGES/services.nowplayer
	msgfmt -o locales/zh-Hant/LC_MESSAGES/services.viki.mo locales/zh-Hant/LC_MESSAGES/services.viki
	msgfmt -o locales/zh-Hant/LC_MESSAGES/services.mewatch.mo locales/zh-Hant/LC_MESSAGES/services.mewatch
	msgfmt -o locales/zh-Hant/LC_MESSAGES/services.youtube.mo locales/zh-Hant/LC_MESSAGES/services.youtube
